---
title: Curriculum Vitae
date: 2024-01-09
date-format: full
format:
  html: default
  docx:
    notes-after-punctuation: true
---

::: {.content-visible when-format='docx'}
Anish S. Shah, MD, MS  
Cell: ***
Pager: *** 
Fax: ***
ORCID ID: [0000-0002-9729-1558](https://orcid.org/0000-0002-9729-1558)  
E-mail: [ashah282@uic.edu](mailto:ashah282@uic.edu)
:::

::: {.content-visible when-format='html'}
Anish S. Shah, MD, MS  
[{{< fa envelope >}}](mailto:ashah282@uic.edu) | 
[{{< fa brands github >}}](https://github.com/shah-in-boots) | 
[{{< fa brands orcid >}}](https://orcid.org/0000-0002-9729-1558) | 
[{{< fa brands google >}}](https://scholar.google.com/citations?hl=en&user=jFGiIJMAAAAJ) | 
[{{< fa globe >}}](https://shah-in-boots.github.io)  
:::

## Personal information

### Physical address

_Office_

University of Illinois Chicago
Division of Cardiology
840 S Wood St
Suite 920, M/C 715
Chicago, IL 60612

_Clinic_

Jesse Brown VA Medical Center
820 S. Damen Avenue
Specialty Clinic, 2nd Floor, Damen Tower
Chicago, IL 60612

_Home_

2810 W. Walton St
Chicago, IL 60622

### Citizenship

United States of America

## Academic and Professional Appointments

### Current Appointments

`2019-present`  
Assistant Professor of Medicine  
Division of Hospital Medicine  
Emory University School of Medicine  

`2019-present`  
Postdoctoral Fellow  
Department of Epidemiology  
Emory University Rollins School of Public Health  

`2019-2020`  
NIH-TL1 Postdoctoral Scholar  
Georgia Clinical and Translational Science Alliance  

## Training

###	Education

`2007-2011`  
Emory University College of Arts and Sciences, Atlanta, Georgia  
_Bachelor of Science in Linguistics and Neurosciences & Behavioral Biology_  

`2012-2016`  
Texas A&M University College of Medicine, College Station, Texas  
_Doctor of Medicine_  

`2019-2020`  
Emory University Laney Graduate School, Atlanta, Georgia  
_Master of Science in Clinical Research_  

###	Postgraduate training

`2016-2019` 
Emory University School of Medicine, Atlanta, Georgia  
_J. Willis Hurst Internal Medicine Residency_  
Distinction in Teaching and Leadership  


###	Licensure and Boards

USMLE Step 1  
USMLE Step 2 CK  
USMLE Step 3  
American Board of Internal Medicine Certification  

## Teaching

### Undergraduate

`2010` 
Emory University College of Arts and Sciences  
Department of Biology  
_Teaching Assistant in Cellular Biology_

`2011-2012` 
North Lake College  
Department of Physics  
_Tutor in Biology, Chemistry, and Physics_

### Medical student

`2013` 
Texas A&M University College of Medicine  
_Histology Tutor_  

`2016` 
Texas A&M University College of Medicine  
Internship Bootcamp  
_Session Leader_  

`2017-2019` 
Emory University School of Medicine  
Physician Assistant Program  
Didactic Experiential Learning Program  
_Faculty Preceptor_

`2018-2019` 
Emory University School of Medicine  
_M3 Ultrasound Workshop Leader_  

`2019` 
Emory University School of Medicine  
_Physical Exam and Clinical Decision Making Workshop Leader_  

###	Medical resident

`2018` 
Emory University School of Medicine  
J. Willis Hurst Internal Medicine Residency Program  
_Lotions and Ointments and Creams, Oh My!_  
Bite-Sized Teaching Mode Conference  
  
`2018` 
Emory University School of Medicine  
J. Willis Hurst Internal Medicine Residency Program  
_The Problem Learner: A history and physical for learners with difficulties_  
Lecture for Distinction in Teaching and Leadership Conference  
  
`2018` 
Emory University School of Medicine  
J. Willis Hurst Internal Medicine Residency Program  
_Intervention of Ischemic Stroke: Thrombectomy in 6 to 16 Hours with Selection by Perfusion Imaging_  
Journal Club Conference  

`2018` 
Emory University School of Medicine  
J. Willis Hurst Internal Medicine Residency Program  
_Ironing Out Transfusions in Sickle Cell_  
Bite-Sized Teaching Mode Conference  

`2019`  
Emory University School of Medicine  
J. Willis Hurst Internal Medicine Residency Program  
_The History of Sudden Cardiac Death: the Role of the Autonomic Nervous System_  
Senior Grand Rounds  

`2019`  
Emory University School of Medicine  
J. Willis Hurst Internal Medicine Residency Program  
Point-of-Care Ultrasonography Elective  
Teaching Attending

###	Faculty

`2017`  
Emory University School of Medicine  
Division of General Medicine and Geriatrics  
Point-of-Care Ultrasound: Parasternal Long Axis

`2018` 
Southern Hospital Medicine Conference  
_Ultrasound Workshop: Cardiac, IVC, Lung, Abdominal Views_  
  
`2018` 
Southern Hospital Medicine Conference  
_"8 Minutes-to-Win-It": Top Inpatient Teaching Sessions by Soon-To-Be-Leaders_  

### Supervisory Roles

__Students__:   
Julie Sommer, PA-S - April 2017 to August 2018  
Grace Helen Frankel, PA-S - February 2019 to June 2019  

__Interns__:   
Ross Bittman - November 2018 (Bite-sized Teaching Mode Conference Coach)  
Arjun Athreya - January 2019 (Bite-sized Teaching Mode Conference Coach)  

## Professional Memberships

`2012-2016` 
Texas Medical Association  
`2012-present` 
American Medical Association  
`2012-present` 
American College of Physicians  
`2018-present` 
American Heart Association  

## Honors and Awards

`2007` 
EMT-Basic National Competition, 1st Place, HOSA  
`2009` 
Delores B. Aldridge Excellence in Service to a Diverse Community Award  
`2009–2011` 
Nu Rho Psi Honor Society  
`2009` 
Speaker to His Holiness the XIV Dalai Lama  
	_Selected to represent Emory students in a meeting with the Dalai Lama in MacLeod Gange, India._
`2013` 
Medical Student Research Program in Diabetes, National Institute of Diabetes and Digestive and Kidney Diseases  
`2015` 
Texas A&M University College of Medicine Research Symposium, 1st Place Oral Presentation  
`2017` 
Doctor’s Dilemma (Medical Jeopardy), Emory’s Resident Team, Georgia ACP Conference  
`2018` 
American Heart Association Scientific Sessions - Top Donors Meeting presentation  
	_Special invitation to discuss research with AHA leadership and top philanthropists._
`2019`
NIH-TL1 Postdoctoral Scholar, Ruth L. Kirschtein National Research Service Award  

## Skills

### Procedural and clinical skills

__Point-of-care ultrasonography__:  
Training included 1 month of ultrasound curriculum and 2 months of emergency medicine ultrasound during medical school, including wilderness medicine training. Further training in residency during ICU, wards, and cardiology rotations. Skills include obtain cardiac views, assessing global cardiac function, identifying pleural disease, IVC assessment, identifying hydronephrosis, and skin/soft tissue evaluation.  

__Procedures__:   
Point-of-care ultrasonography  
Arterial line placement (radial, brachial, dorsalis pedis) - 52  
Arthrocentesis (knee, ankle, shoulder) - 31  
Central line placement (internal jugular, femoral, subclavian) - 84  
Lumbar puncture - 34  
Thoracentesis - 19  
Paracentesis - 24  

###	Languages spoken
  
English  
Gujurati  
Spanish  

### Technical skills

__Computer programming:__  
R, RStudio - scripting language and environment for statistical computing and graphics  
PERL - high-level programming language for text processing and manipulation  
C++ - low-level programming language for data processing  
Vim - command line editing  
Markdown - syntax for formatting of writing  
Git, Github - version control system  
MATLAB - matrix-oriented mathematical programming language  

### Certifications

`2007-2010` 
EMT-B  
  
`2012—2016` 
ATLS  
  
`2012—present` 
ACLS  
  
`2015—present` 
PADI Open Water Diver  
  
`2016—present` 
Wilderness First Responder  
  
`2017—present` 
ASA 101 Basic Keelboat  

## Conferences

###	Institutional  
  
`2009` 
_Cortisol Levels in Rhesus Monkeys with Maternal Separation Over Longitudinal Cohorts_  
__Anish Shah__, Mar Sanchez PhD  
Poster Presentation  
Scholarly Inquiry and Research at Emory Research Partners Symposium  
Atlanta, Georgia  
  
`2016` 
_Long-Term Outcomes of Newborns with Necrotizing Enterocolitis: a retrospective matched cohort study_  
__Anish Shah__, Emily Sanders*, Mary Mrdutt MD, Lena Perger MD  
Texas A&M University College of Medicine Research Symposium, 1st Place  
Temple, Texas  
  
`2016` 
_Long-Term Outcomes of Newborns with Necrotizing Enterocolitis: a retrospective matched cohort study_  
__Anish Shah__, Emily Sanders, Mary Mrdutt MD, Lena Perger MD  
Scott & White Healthcare Academic Operations Research Day  
Temple, Texas  
  
`2018` 
_Association of Ischemia with Heart Rate Variability_  
__Anish Shah MD__, Amit Shah MD MSCR  
Poster Presentation  
Emory Internal Medicine Resident Research Day  
Atlanta, Georgia  
  
`2018` 
_The Largest IVC: the examination of torrential tricuspid regurgitation in the setting of peripartum cardiomyopathy_  
Birju Rao MD*, __Anish Shah MD__, Stephen D. Clements MD  
Poster Presentation  
Mr. William E. Booth and Dr. James Zaidan Grady Resident Research Day  
Atlanta, Georgia  
  
`2018` 
_More than Mono: Epstein Barr virus mimicking malignancy_  
Gabriel Aleixo*, __Anish Shah MD__, Fuad El Rassi MD  
Poster Presentation  
Mr. William E. Booth and Dr. James Zaidan Grady Resident Research Day  
Atlanta, Georgia  
  
`2018` 
_Association of Ischemia with Heart Rate Variability_  
__Anish Shah MD__, Amit Shah MD MSCR  
Poster Presentation  
Mr. William E. Booth and Dr. James Zaidan Grady Resident Research Day  
Atlanta, Georgia  
  
`2019` 
_Association of Psychosocial Factors with Heart Rate Variability: The Atherosclerosis Risk in Communities Study_  
__Anish Shah MD__, Alvaro Alonso MD PhD, Amit Shah MD MSCR  
Poster Presentation  
Emory University Department of Medicine Research Day  
Atlanta, Georgia  
  

### Regional  
  
`2011` 
_Influence of the Acoustic Parameter of Pitch on Emotion and Focus Location in Statements using Ditransitive Verb Manipulations_  
__Anish Shah__, Yu Li PhD  
Poster Presentation  
Great Lakes Expo for Experimental and Formal Undergraduate Linguistics, Michigan State University, East Lansing, Michigan  
  
`2015` 
_Illuminating the Case of a Rare GI Bleed_  
__Anish Shah__, Austin Metting MD  
Poster Presentation  
American College of Physicians Texas Chapter Conference  
  
`2017` 
_Three’s company: nocardiosis, neuroendocrine hyperplasia, and breast cancer_  
__Anish Shah MD__, Stephen D. Clements MD, Matthew Dudgeon MD PhD  
Poster Presentation  
American College of Physicians Georgia Chapter Conference  
Savannah, Georgia  
  
`2017` 
_Three’s company: nocardiosis, neuroendocrine hyperplasia, and breast cancer_  
__Anish Shah MD__, Stephen D. Clements MD, Matthew Dudgeon MD PhD  
Poster Presentation  
Southern Hospital Medicine Conference  
New Orleans, Louisiana  
  

### National  
  
`2014` 
_Genetic Linkage Analysis for Cystic Fibrosis Related Diabetes_  
__Anish Shah__, Scott Blackman MD PhD  
Poster Presentation  
NIDDK Medical Student Research Symposium at Vanderbilt University  
Vanderbilt University, Nashville, Tennessee  
  
`2017` 
_Long-Term Outcomes of Newborns with Necrotizing Enterocolitis: a retrospective matched cohort study_  
__Anish Shah__, Emily Sanders, Mary Mrdutt MD*, Lena Perger MD  
Oral Presentation  
Annual Meeting of the Canadian Association of Pediatric Surgery  
Vancouver, Canada  
  
`2018` 
_Circadian Autonomic Inflexibility: a Marker of Ischemic Heart Disease_  
__Anish Shah MD__*, Rachel Lampert MD, Jack Goldberg PhD, J. Douglas Bremner MD, Lian Li PhD, Marc Thames MD, Viola Vaccarino MD PhD, Amit Shah MD MSCR  
Poster Presentation  
American Heart Association Scientific Sessions  
Chicago, Illinois  

## Research

### Funding

`2019-2020`  
Postdoctoral Scholar, NIH-TL1 Training Grant  
Georgia Clinical and Translational Science Alliance  
_Disturbances of the Neurocardiac Axis: Using Heart Rate Variability to Measure Disease in the Brain and Heart_  
Grant: TL1TR002382, UL1TR002378  


### Manuscripts

__Shah, AS__, Lampert R, Goldberg, J, Bremner, JD, Thames, MD, Vaccarino, V, Shah, AJ. "Circadian Changes in Heart Rate Variability Predict Abnormal Myocardial Perfusion". [under review] 

### Works in progress

Mrdutt, M, __Shah, AS__, Sanders, Mallett, L, Perger, LP. “Long-Term Outcomes of Newborns with Necrotizing Enterocolitis: a retrospective matched cohort study”. Canadian Association of Pediatric Surgery Edition of the Journal of Pediatric Surgery, May 2017 [accepted]  

__Shah, AS__, Alvaro, A, Whitsel, E, Vaccarino, V, Shah, AJ. “Heart Rate Variability and Psychosocial States: the Atherosclerosis Risk In Communities study”. [pending]  

__Shah, AS__, Clements, SD, Dudgeon, M. "Nocardioma: neuroendocrine hyperplasia as a response to pulmonary nocardiosis". Annals of Internal Medicine. [pending]

__Shah, AS__, Klein, R, Akbashev, M. "Cardiovascular Ultrasonography in Resident Learning and Clinical Decision Making" [pending]

Park, J, __Shah, AS__, Mehta, PK, Shah, AJ, Quyyumi, AA, Vaccarino, V, Marvar, P. "Brain-Heart Interactions in Stress and Anxiety Related Disorders: Implications for Increased Cardiovascular Disease Risk". Hypertension. [pending]

 __Shah, AS__, Shah, AJ, Mehta, PK, Thames, MD. "Sympathetic Innervation of the Heart: a Clinical Review". [pending]

### Published abstracts  

`2014` 
__Shah, AS__, Blackman, S. “Genetic Linkage Analysis for Cystic Fibrosis Related Diabetes”. National Institute of Diabetes and Digestive and Kidney Diseases Medical Student Research Symposium at Vanderbilt University, Nashville, Tennessee. 
  
`2017` 
Mrdutt, M, __Shah, AS__, Sanders, E, Mallett, L, Perger, LP. “Long-Term Outcomes of Newborns with Necrotizing Enterocolitis: a retrospective matched cohort study”. Annual Meeting of the Canadian Association of Pediatric Pediatric Surgeons, Vancouver, British Columbia, Canada.
  
`2017` 
__Shah, AS__, Clements, SD, Dudgeon, M. “Three’s company: nocardiosis, neuroendocrine hyperplasia, and breast cancer”. Southern Hospital Medicine Conference, New Orleans, Louisiana.  
  
`2018` 
__Shah, AS__, Lampert R, Goldberg, J, Bremner, JD, Vaccarino, V, Shah, AJ. “Circadian Autonomic Inflexibility: a Marker of Ischemic Heart Disease”. Circulation. 

## References

### Academic

Amit Shah, MD, MSCR  
Assistant Professor of Epidemiology Assistant Professor of Medicine (Cardiology)  
1518 Clifton Rd. NE, Rm 3053  
Atlanta, GA 30322 
Email: ajshah3@emory.edu  
Phone – 404-727-8712  

### Clinical

Anna Kho, MD  
Associate Professor of Medicine  
Division of General Medicine and Geriatrics  
Emory University School of Medicine  
49 Jesse Hill Jr. Dr. S.E.  
Atlanta, GA 30303  
Email: apham@emory.edu  
Office: 404-778-1626  
Fax: 404-778-1601  

Ananth Vadde, MD  
Instructor of Medicine  
Division of Hospital Medicine  
Emory University School of Medicine  
Email: ananth.vadde@emory.edu  

David Krakow, MD  
Master Clinician  
Assistant Professor of Medicine  
Division of Hospital Medicine  
Emory University School of Medicine  
Email: dkrakow@emory.edu  
Office: 404-686-7869  

Natasha Travis, MD  
Assistant Professor of Medicine  
Division of General Medicine and Geriatrics  
Emory University School of Medicine  
49 Jesse Hill Jr. Dr. S.E.  
Atlanta, GA 30303  
Email: natasha.travis@emory.edu  
Office: 404-686-8181  

### Ultrasonography

Mikhail Akbashev, MD  
Course Director and Clinical Lead - Point-of-Care Ultrasound  
Assistant Professor  
Division of General Medicine and Geriatrics  
Emory University School of Medicine  
Email: makbash@emory.edu  

Shirine Allam  
Assistant Professor of Medicine  
Associate Program Director - Pulmonary, Allergy, Critical Care Fellowship  
Emory University School of Medicine  
Email: shirine.allam@emory.edu  
