---
name: Anish Sanjay Shah
date: "`r format(Sys.time(), '%B %D, %Y')`"
position: "Cardiology Fellow"
address: "Division of Cardiology, University of Illinois Chicago, Chicago, IL, 60607"
email: "ashah282@uic.edu"
phone: 312-839-5619
fax: 226-589-5000
www: asshah4.github.io
github: asshah4
twitter: shah_in_boots
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(tidyr)
library(dplyr)
library(glue)
library(readr)
```

# About Me

Cardiology fellow with an interest in autonomic dysfunction, heart rate variability, epidemiology, biostatistics, and point-of-care ultrasonography.

# Academic

## Degrees

```{r education}
read_csv("data/positions.csv") %>%
	filter(section == "education") %>%
	arrange(start) %>%
	detailed_entries(
		when = glue("{start}--{end}"),
		what = title,
		where = location,
		with = institution,
		why = description
	) 
```

## Clinical Training

```{r training}
read_csv("data/positions.csv") %>%
	filter(section == "training") %>%
	arrange(start) %>%
	detailed_entries(
		when = glue("{start}--{end}"),
		what = title,
		where = location,
		with = institution,
		why = description
	) 
```

## Current Appointments

```{r appts}
read_csv("data/positions.csv") %>%
	filter(section == "appointments") %>%
	arrange(start) %>%
	detailed_entries(
		when = glue("{start}--{end}"),
		what = title,
		where = location,
		with = institution,
		why = description
	) 
```

# Honors and Awards

```{r awards}
read_csv("data/honors.csv") %>%
	filter(section == "awards") %>%
	arrange(desc(start)) %>%
	detailed_entries(
		when = case_when(
			is.na(end) ~ glue("{start}"),
			!is.na(end) ~ glue("{start}--{end}")
		),
		what = title,
		where = location,
		with = institution,
		why = description
	) 
```

# Teaching

## Teaching Responsibilities

```{r teaching}
read_csv("data/academic.csv") %>%
	filter(section == "teaching") %>%
	arrange(desc(start)) %>%
	detailed_entries(
		when = case_when(
			is.na(end) ~ glue("{start}"),
			!is.na(end) ~ glue("{start}--{end}")
		),
		what = title,
		where = location,
		with = institution,
		why = description
	) 
```

## Educational Lectures

```{r talks}
read_csv("data/academic.csv") %>%
	filter(section == "talks") %>%
	arrange(desc(start)) %>%
	detailed_entries(
		when = case_when(
			is.na(end) ~ glue("{start}"),
			!is.na(end) ~ glue("{start}--{end}")
		),
		what = title,
		where = location,
		with = institution,
		why = description
	) 
```

# Research

## Conferences

```{r conferences}
bibliography_entries("../bibliography/Publications.bib") %>%
	filter(type == "paper-conference") %>%
	arrange(issued) %>%
	select(-c(volume, issue, abstract, URL, DOI, ISSN, page, keyword, PMID))
```

## Publications

```{r pubs}
bibliography_entries("../bibliography/Publications.bib") %>%
	filter(type == "article-journal") %>%
	arrange(issued) %>%
	select(-c(issue, ISSN, publisher, page, keyword, PMID, `publisher-place`))
```

